version: '3'

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./.env/:/vpn
    networks:
      - vpn_network
  adt_send_hw:
    build: ./adt_send_hw
    volumes:
      - ./.env/:/adt_send_hw/
    networks:
      - vpn_network
    depends_on:
      - vpn
    environment:
      ENV_PATH: /adt_send_hw/.env/adt_send_hw.env


networks:
  vpn_network:
    driver: bridge

