version: '3'

services:
  vpn:
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./.env/:/vpn
    networks:
      - vpn_network
    ports:
    - "8080:3001"
    restart: "on-failure:10"
  adt_send_hw:
    build: ./adt_send_hw
    volumes:
      - ./.env/:/adt_send_hw/.env/
    # networks:
    #   - vpn_network
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      ENV_PATH: /adt_send_hw/.env/adt_send_hw.env
    restart: "on-failure:5"
    

networks:
  vpn_network:
    driver: bridge

